accounts:
  - name: eg-authority
    coins: ["20000aut", "200000000stake"]
  - name: uk-authority
    coins: ["20000aut", "200000000stake"]
  - name: sa-authority
    coins: ["20000aut", "200000000stake"]
  - name: au-authority
    coins: ["20000aut", "200000000stake"]
  - name: ca-authority
    coins: ["20000aut", "200000000stake"]
  - name: fr-authority
    coins: ["20000aut", "200000000stake"]
  - name: ge-authority
    coins: ["20000aut", "200000000stake"]
  - name: ru-authority
    coins: ["20000aut", "200000000stake"]
  - name: bf-authority
    coins: ["20000aut", "200000000stake"]
  - name: br-authority
    coins: ["20000aut", "200000000stake"]
    
validator:
  name: "eg-authority"
  staked: "10000000stake"
  
faucet:
  host: ":4501"
  name: eg-authority
  coins: ["5aut", "100000stake"]
  
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"

init:
  home: "$HOME/.master"
  
host:
  rpc: ":26659"
  p2p: ":26658"
  prof: ":6061"
  grpc: ":9092"
  grpc-web: ":9093"
  api: ":1318"
